use crate::cfg::mmconf::MinionConfig;
use crate::traits::systraits::SystemTraits;
use crate::traits::{MASTER_TRAITS_FILE, TraitUpdateRequest, current_os_type, effective_profiles, ensure_master_traits_file, os_display_name};
use std::fs;

#[test]
fn ensure_master_traits_file_creates_reserved_master_cfg() {
    let root = tempfile::tempdir().unwrap_or_else(|err| panic!("failed to create tempdir: {err}"));
    let mut cfg = MinionConfig::default();
    cfg.set_root_dir(root.path().to_str().unwrap_or_default());

    ensure_master_traits_file(&cfg).unwrap_or_else(|err| panic!("failed to ensure master traits file: {err}"));

    let pth = cfg.traits_dir().join(MASTER_TRAITS_FILE);
    assert!(pth.exists(), "master-managed traits file should exist");

    let content = fs::read_to_string(pth).unwrap_or_else(|err| panic!("failed to read master traits file: {err}"));
    assert!(content.contains("AUTOGENERATED"), "master-managed traits header should be present");
}

#[test]
fn trait_update_request_set_writes_master_managed_traits() {
    let root = tempfile::tempdir().unwrap_or_else(|err| panic!("failed to create tempdir: {err}"));
    let mut cfg = MinionConfig::default();
    cfg.set_root_dir(root.path().to_str().unwrap_or_default());

    TraitUpdateRequest::from_context(r#"{"op":"set","traits":{"foo":"bar","count":3}}"#)
        .unwrap_or_else(|err| panic!("failed to parse traits update: {err}"))
        .apply(&cfg)
        .unwrap_or_else(|err| panic!("failed to apply traits update: {err}"));

    let content =
        fs::read_to_string(cfg.traits_dir().join(MASTER_TRAITS_FILE)).unwrap_or_else(|err| panic!("failed to read master traits file: {err}"));
    assert!(content.contains("foo: bar"));
    assert!(content.contains("count: 3"));
}

#[test]
fn trait_update_request_unset_removes_keys_from_master_managed_traits() {
    let root = tempfile::tempdir().unwrap_or_else(|err| panic!("failed to create tempdir: {err}"));
    let mut cfg = MinionConfig::default();
    cfg.set_root_dir(root.path().to_str().unwrap_or_default());

    let set = TraitUpdateRequest::from_context(r#"{"op":"set","traits":{"foo":"bar","keep":"yes"}}"#)
        .unwrap_or_else(|err| panic!("failed to parse set request: {err}"));
    set.apply(&cfg).unwrap_or_else(|err| panic!("failed to apply set request: {err}"));

    let unset = TraitUpdateRequest::from_context(r#"{"op":"unset","traits":{"foo":null}}"#)
        .unwrap_or_else(|err| panic!("failed to parse unset request: {err}"));
    unset.apply(&cfg).unwrap_or_else(|err| panic!("failed to apply unset request: {err}"));

    let content =
        fs::read_to_string(cfg.traits_dir().join(MASTER_TRAITS_FILE)).unwrap_or_else(|err| panic!("failed to read master traits file: {err}"));
    assert!(!content.contains("foo:"));
    assert!(content.contains("keep: yes"));
}

#[test]
fn trait_update_request_reset_clears_master_managed_traits_file_body() {
    let root = tempfile::tempdir().unwrap_or_else(|err| panic!("failed to create tempdir: {err}"));
    let mut cfg = MinionConfig::default();
    cfg.set_root_dir(root.path().to_str().unwrap_or_default());

    let set =
        TraitUpdateRequest::from_context(r#"{"op":"set","traits":{"foo":"bar"}}"#).unwrap_or_else(|err| panic!("failed to parse set request: {err}"));
    set.apply(&cfg).unwrap_or_else(|err| panic!("failed to apply set request: {err}"));

    let reset =
        TraitUpdateRequest::from_context(r#"{"op":"reset","traits":{}}"#).unwrap_or_else(|err| panic!("failed to parse reset request: {err}"));
    reset.apply(&cfg).unwrap_or_else(|err| panic!("failed to apply reset request: {err}"));

    let content =
        fs::read_to_string(cfg.traits_dir().join(MASTER_TRAITS_FILE)).unwrap_or_else(|err| panic!("failed to read master traits file: {err}"));
    assert!(content.contains("AUTOGENERATED"));
    assert!(!content.contains("foo:"));
}

#[test]
fn unset_removes_key_from_separate_cfg_file() {
    let root = tempfile::tempdir().unwrap();
    let mut cfg = MinionConfig::default();
    cfg.set_root_dir(root.path().to_str().unwrap_or_default());

    ensure_master_traits_file(&cfg).unwrap();
    fs::write(cfg.traits_dir().join("jedi.cfg"), "name: Yoda\nsaber: green\n").unwrap();

    let set = TraitUpdateRequest::from_context(r#"{"op":"set","traits":{"name":"Anakin"}}"#).unwrap();
    set.apply(&cfg).unwrap();

    let unset = TraitUpdateRequest::from_context(r#"{"op":"unset","traits":{"name":null}}"#).unwrap();
    unset.apply(&cfg).unwrap();

    let master = fs::read_to_string(cfg.traits_dir().join(MASTER_TRAITS_FILE)).unwrap();
    assert!(!master.contains("name:"), "name should be gone from master.cfg");

    let jedi = fs::read_to_string(cfg.traits_dir().join("jedi.cfg")).unwrap();
    assert!(!jedi.contains("name:"), "name should be gone from jedi.cfg");
    assert!(jedi.contains("saber: green"), "unrelated key preserved in jedi.cfg");
}

#[test]
fn unset_preserves_yaml_order_in_cfg_files() {
    let root = tempfile::tempdir().unwrap();
    let mut cfg = MinionConfig::default();
    cfg.set_root_dir(root.path().to_str().unwrap_or_default());

    ensure_master_traits_file(&cfg).unwrap();
    fs::write(cfg.traits_dir().join("rebels.cfg"), "rank: General\nalias: Fulcrum\nhome: Yavin\n# comment\n").unwrap();

    let unset = TraitUpdateRequest::from_context(r#"{"op":"unset","traits":{"alias":null}}"#).unwrap();
    unset.apply(&cfg).unwrap();

    let rebels = fs::read_to_string(cfg.traits_dir().join("rebels.cfg")).unwrap();
    assert!(!rebels.contains("alias:"));
    let rank_pos = rebels.find("rank:").unwrap();
    let home_pos = rebels.find("home:").unwrap();
    assert!(rank_pos < home_pos, "order preserved after key removal");
}

#[test]
fn unset_idempotent_on_missing_key() {
    let root = tempfile::tempdir().unwrap();
    let mut cfg = MinionConfig::default();
    cfg.set_root_dir(root.path().to_str().unwrap_or_default());

    ensure_master_traits_file(&cfg).unwrap();
    fs::write(cfg.traits_dir().join("jedi.cfg"), "saber: blue\n").unwrap();

    let unset = TraitUpdateRequest::from_context(r#"{"op":"unset","traits":{"nonexistent":null}}"#).unwrap();
    unset.apply(&cfg).unwrap();

    let jedi = fs::read_to_string(cfg.traits_dir().join("jedi.cfg")).unwrap();
    assert!(jedi.contains("saber: blue"), "unrelated file untouched");
}

#[test]
fn empty_master_traits_file_is_accepted_during_trait_load() {
    let root = tempfile::tempdir().unwrap_or_else(|err| panic!("failed to create tempdir: {err}"));
    let mut cfg = MinionConfig::default();
    cfg.set_root_dir(root.path().to_str().unwrap_or_default());

    ensure_master_traits_file(&cfg).unwrap_or_else(|err| panic!("failed to ensure master traits file: {err}"));

    let traits = SystemTraits::new(cfg, true);
    assert!(!traits.has("foo"), "header-only master.cfg should not inject traits");
}

#[test]
fn effective_profiles_fallback_to_default_and_dedup_array_values() {
    let root = tempfile::tempdir().unwrap_or_else(|err| panic!("failed to create tempdir: {err}"));
    let mut cfg = MinionConfig::default();
    cfg.set_root_dir(root.path().to_str().unwrap_or_default());

    ensure_master_traits_file(&cfg).unwrap_or_else(|err| panic!("failed to ensure master traits file: {err}"));
    assert_eq!(effective_profiles(&cfg), vec!["default".to_string()]);

    fs::write(cfg.traits_dir().join(MASTER_TRAITS_FILE), "minion.profile:\n  - Foo\n  - Bar\n  - Foo\n")
        .unwrap_or_else(|err| panic!("failed to write master traits file: {err}"));
    assert_eq!(effective_profiles(&cfg), vec!["Foo".to_string(), "Bar".to_string()]);
}

#[test]
fn effective_profiles_drops_default_when_real_profiles_are_present() {
    let root = tempfile::tempdir().unwrap_or_else(|err| panic!("failed to create tempdir: {err}"));
    let mut cfg = MinionConfig::default();
    cfg.set_root_dir(root.path().to_str().unwrap_or_default());

    ensure_master_traits_file(&cfg).unwrap_or_else(|err| panic!("failed to ensure master traits file: {err}"));
    fs::write(cfg.traits_dir().join(MASTER_TRAITS_FILE), "minion.profile:\n  - default\n  - Runtimes\n")
        .unwrap_or_else(|err| panic!("failed to write master traits file: {err}"));
    assert_eq!(effective_profiles(&cfg), vec!["Runtimes".to_string()]);
}

#[test]
fn os_display_name_keeps_android_distinct_from_linux() {
    assert_eq!(os_display_name("android"), "Android");
    assert_eq!(os_display_name("linux"), "Linux");
    assert!(!current_os_type().is_empty(), "current os type should be available");
}
