/*
 * SysInspect API
 *
 * SysInspect Web API for interacting with the master interface.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthResponse {
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "sid_cipher")]
    pub sid_cipher: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "symkey_cipher")]
    pub symkey_cipher: String,
}

impl AuthResponse {
    pub fn new(error: String, sid_cipher: String, status: String, symkey_cipher: String) -> AuthResponse {
        AuthResponse {
            error,
            sid_cipher,
            status,
            symkey_cipher,
        }
    }
}

