/*
 * SysInspect API
 *
 * SysInspect Web API for interacting with the master interface.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthResponse {
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "sid")]
    pub sid: String,
    #[serde(rename = "status")]
    pub status: String,
}

impl AuthResponse {
    pub fn new(error: String, sid: String, status: String) -> AuthResponse {
        AuthResponse {
            error,
            sid,
            status,
        }
    }
}

