/*
 * SysInspect API
 *
 * SysInspect Web API for interacting with the master interface.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthRequest {
    /// Base64-encoded, RSA-encrypted JSON: {\"username\": \"...\", \"password\": \"...\", \"pubkey\": \"...\"}
    #[serde(rename = "payload")]
    pub payload: String,
    #[serde(rename = "pubkey")]
    pub pubkey: String,
}

impl AuthRequest {
    pub fn new(payload: String, pubkey: String) -> AuthRequest {
        AuthRequest {
            payload,
            pubkey,
        }
    }
}

