/*
 * SysInspect API
 *
 * SysInspect Web API for interacting with the master interface.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HealthResponse {
    #[serde(rename = "info")]
    pub info: Box<models::HealthInfo>,
    #[serde(rename = "status")]
    pub status: String,
}

impl HealthResponse {
    pub fn new(info: models::HealthInfo, status: String) -> HealthResponse {
        HealthResponse {
            info: Box::new(info),
            status,
        }
    }
}

