/*
 * SysInspect API
 *
 * SysInspect Web API for interacting with the master interface.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HealthInfo {
    #[serde(rename = "api_version")]
    pub api_version: String,
    #[serde(rename = "scheduler_tasks")]
    pub scheduler_tasks: i32,
    #[serde(rename = "telemetry_enabled")]
    pub telemetry_enabled: bool,
}

impl HealthInfo {
    pub fn new(api_version: String, scheduler_tasks: i32, telemetry_enabled: bool) -> HealthInfo {
        HealthInfo {
            api_version,
            scheduler_tasks,
            telemetry_enabled,
        }
    }
}

