/*
 * SysInspect API
 *
 * SysInspect Web API for interacting with the master interface.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MasterKeyError {
    #[serde(rename = "error")]
    pub error: String,
}

impl MasterKeyError {
    pub fn new(error: String) -> MasterKeyError {
        MasterKeyError {
            error,
        }
    }
}

