/*
 * SysInspect API
 *
 * SysInspect Web API for interacting with the master interface.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MasterKeyResponse {
    #[serde(rename = "key")]
    pub key: String,
}

impl MasterKeyResponse {
    pub fn new(key: String) -> MasterKeyResponse {
        MasterKeyResponse {
            key,
        }
    }
}

