/*
 * SysInspect API
 *
 * SysInspect Web API for interacting with the master interface.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelNameResponse {
    #[serde(rename = "models")]
    pub models: Vec<String>,
}

impl ModelNameResponse {
    pub fn new(models: Vec<String>) -> ModelNameResponse {
        ModelNameResponse {
            models,
        }
    }
}

