/*
 * SysInspect API
 *
 * SysInspect Web API for interacting with the master interface.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelResponse {
    #[serde(rename = "model")]
    pub model: Box<models::ModelInfo>,
}

impl ModelResponse {
    pub fn new(model: models::ModelInfo) -> ModelResponse {
        ModelResponse {
            model: Box::new(model),
        }
    }
}

