/*
 * SysInspect API
 *
 * SysInspect Web API for interacting with the master interface.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PubKeyRequest : Push to push a user public key to store on the server.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PubKeyRequest {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "sid")]
    pub sid: String,
}

impl PubKeyRequest {
    /// Push to push a user public key to store on the server.
    pub fn new(key: String, sid: String) -> PubKeyRequest {
        PubKeyRequest {
            key,
            sid,
        }
    }
}

