/*
 * SysInspect API
 *
 * SysInspect Web API for interacting with the master interface.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PubKeyResponse {
    #[serde(rename = "message")]
    pub message: String,
}

impl PubKeyResponse {
    pub fn new(message: String) -> PubKeyResponse {
        PubKeyResponse {
            message,
        }
    }
}

