/*
 * SysInspect API
 *
 * SysInspect Web API for interacting with the master interface.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryRequest {
    #[serde(rename = "nonce")]
    pub nonce: String,
    #[serde(rename = "payload")]
    pub payload: String,
    #[serde(rename = "sid_rsa")]
    pub sid_rsa: String,
}

impl QueryRequest {
    pub fn new(nonce: String, payload: String, sid_rsa: String) -> QueryRequest {
        QueryRequest {
            nonce,
            payload,
            sid_rsa,
        }
    }
}

