/*
 * SysInspect API
 *
 * SysInspect Web API for interacting with the master interface.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryResponse {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "status")]
    pub status: String,
}

impl QueryResponse {
    pub fn new(message: String, status: String) -> QueryResponse {
        QueryResponse {
            message,
            status,
        }
    }
}

