[package]
name = "proc"
version = "0.1.0"
edition = "2021"

[dependencies]
libsysinspect = { path = "../../../libsysinspect" }
sysinfo = { version = "0.31.4", features = ["linux-netdevs", "linux-tmpfs"] }
