on:
  push:
    branches:
      - "master"
  pull_request:

name: Insanity check
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add clippy
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler llvm-dev clang libclang-dev cmake libsodium-dev libpam0g-dev
      - run: make check
